### ISSUE TITLE
SchoolSemester in der API

### ISSUE THREAD

**Issue by SiekmannITC** [school-data-hub/school-data-hub#3]
Momentan sieht es so aus, dass alle Objekte, die mit einem Schoolday zu tun haben (MissedClass, SchooldayEvent) "nested" an den Pupils gezogen werden. Im Grunde sollten hier <https://github.com/school-data-hub/school-data-hub/blob/f66535cfc6025dc5e6c27c3ee66c1534e73e1ef4/backend/api_endpoints/pupils_api.py#L228>  nur die Objekte aus dem aktuellen Schuljahr heruntergeladen werden, d.h. alle Objekte, die im aktuellen Semester stattgefunden haben (bzw. im 2. Semester des Schuljahres die aus dem Vorsemester ("is_first":true ) auch dazu).

**Comment by dabblingwithcode** [comment]
This seems to work, thanks! Can we merge?
In the long run, we'll probably need endpoints for past semesters.
